= Testing Module (moduleId 12)

== Purpose
The Testing Module is designed to automate tests for battery and throughput measurements.

== Functionality

The Testing Module has two roles.

* Master: Testing Module by default starts in test role "Master". Master node initialises the tests by sending a start test message to the node  which will perform tests.
* Slave: Testing Module changes its role to slave when it receives a message to start test.

== Test Applications
The applications currently being tested are Advertisement, Scanning, LED, Latency and Connection Tests.

=== Advertisement Test:
Advertisement test is performed by using different values of following advertisement parameters.

===== Advertisement Type:
Advertisement types used by Testing Module are

* Connectable Undirected: Advertisement type where any device can send scan response packet and connect request to the advertiser.

* Non Connectable Undirected: Advertisement type where advertiser will not accept any connect request or scan request.

===== Advertisement Interval
Advertisement Interval specifies the intervening time between advertising messages. The advertisement interval used by Testing Module are 20ms, 100ms, 1000ms and 4000ms

===== Payload Size
Payload size is the size of the packet to be advertised. Payload of size 10 bytes and 30 bytes are advertised by Testing Module.

===== Transmit Power
Testing Module advertise packets with Tx power 0dbm and 4dbm.


=== Scanning Test:
Scanning test is performed by using different values of following scanning parameters.

* Scan for 3ms window in every 20ms interval.
* Scan for 10ms window in every 10ms interval (full duty cycle).

=== Latency Test:
Master node sends a packet to slave node. The slave node immediately sends a packet back to the master node. Master node keeps the track of time from start of sending until all packets are received.

=== LED Test
Slave node switches on red LED for 10 sec and do nothing and then switches on green led and do nothing.

=== Connection Test
Master node generates as many packets as possible, each 20 byte payload and count number of packets successfully put in the send queue.

== Terminal Commands

=== starttest
starttest takes ble address and application number as an input and start test by sending a message to slave
[source, C++]
----
//Receiving nodes will switch to slave node and start test
action [nodeId] testing starttest [bleAddress] {applicationToTest}
---


