= Developers

== File Structure
This is a list and description of the most important folders in the repository.

----
├── config/                   configuration header files
├── └── featuresets/          different build configurations
├── inc/                      main include directory for C++ headers
├── ├── c/                    includes for c code
├── └── nrf52/                specific nrf52 includes
├── inc_c/                    include directory for C headers
├── linker/                   linker scripts
├── sdk/                      modified nRF SDKs
├── softdevice/               softdevice hex files
├── src/                      
├── ├── base/                 wrappers for BLE stack functionality
├── ├── c/                    drivers and other c code
├── ├── mesh/                 mesh functionality
├── ├── modules/              functionality wrapped in modules
├── ├── utility/              helper classes
├── ├── Boardconfig.cpp       runtime pin and board configuration
├── ├── Config.cpp            configuration
├── ├── FruityMesh.cpp        bootup and main functionality
├── ├── GlobalState.cpp       holds references to basic classes
├── └── Main.cpp              Startup Code
├── util/                     tools and utilities
└── src_examples/             code templates and examples
----

Functionality that is not part of the meshing algorithm should be placed in the `fruitymesh/modules/` folder and the module class extended. A module receives all events that it is interested in and can save and load its configuration from flash memory.

Have a look at xref:Class-Structure.adoc[Class Structure] for some more detailed explanations on how the code is structured. Also keep in mind xref:CherrySim.adoc[Instances] when implementing new functionalities.

There are some utilities in the `/util` folder, for example a python script that opens a putty terminal for all connected serial devices and a Wireshark dissector that can be used together with the nRF Sniffer to inspect the advertising packets.

== Configuring FruityMesh
Most settings are found in the `fruitymesh/src/` folder in `Config.h` but should be configured in the Featuresets. Module specific settings are kept within the module's header and cpp file.

[#Featuresets]
== Feature Sets
FruityMesh uses so called featuresets for creating different distributions for different use-cases. A featureset defines the compile time and run time configuration for a node. The cmake build process can be configured differently for a featureset, a number of different defines or macros can be used during compile time and different code is used during runtime. This allows us to tailor the firmware functionality and size to each use-case and also allows FruityMesh to compile for different chipsets from the same source. You can specify the featureset by calling cmake with `cmake --build . --target featureset_name`.

A featureset can contain a number of xref:BoardConfig.adoc[Board Configurations] which allows you to flash and run the binary of the featureset on a number of different boards. The correct board configuration such as the pin configuration is then loaded by FruityMesh at runtime depending on the boardId stored in the xref:Specification.adoc#UICR[UICR]. If no boardId is stored in the UICR, the default boards will be loaded from `Boardconfig.cpp`

== Memory Requirements
FruityMesh doesn't run on devices with only 16kb of RAM. It may be possible to optimize the build and resize some buffers, but this is currently not supported. The binary of FruityMesh is around 50kb depending on the configuration and will easily fit on devices with 256kb flash together with the softdevice and still be updatable using dual bank updates.

== Want To Contribute?
All kinds of contributions are welcome. Before you start coding, please contact us to align the development process.

== About Questions
If you have a general question, the best way is to open a new issue and label it with "question". This way, a knowledge base of questions and answers is maintained for easy access in the future. If it is a commit-specific comment or question, you can just comment under the commit.

== About Forking
We'd love to develop the FruityMesh protocol as an interoperable protocol that works across devices from different developers. If you want to make any changes to the protocol itself, please contact us first so that we can work out a mutual agreement. Every implementation that is compatible with the current official release of FruityMesh is welcome to use the M-Way Solutions Company identifier (0x024D) in the manufacturer specific data along with the current mesh identifier. Be sure to read the xref:Specification.adoc[Specification] for some basics. This is only very basic documentation, we try to continually improve the specification and add more details. In the meantime, do not hesitate to contact us or have a look in the implementation.

== About Documentation
When adding documentation for a module, make sure to check the xref:ModuleDocumentationTemplate.adoc[Module Documentation Template].

== About Contributions
The implementation is written in C++. This makes it easy to implement new functionality and separate it from other parts in a clean way. Refactoring or refinement tips are welcome. If you contribute, please comment your code thorougly and keep the implementation as readable as possible. This will help other contributors understand the code quickly.
If you have documentation to add, please post a pull request as well.

== Licence
FruityMesh is published under the GPLv3 version, which is available in the repository.
