= FAQ

== Where To Ask Questions?
Just open a new issue and tag it with the label "question". You can find all user questions on this page:

**https://github.com/mwaylabs/fruitymesh/issues?q=label%3Aquestion[FruityMesh Questions]**

== Can I use FruityMesh with chipset XXXX?
The answer is: Not easily. FruityMesh has been developed on the Nordic nRF Series. This includes the nRF52832 and nRF52840. It needs the S132 or S140 Softdevice, which provides a Bluetooth Low Energy stack that supports concurrent operations as Peripheral/Central/Advertiser and Observer. Connection and disconnection are managed by the FruityMesh algorithm but having concurrent operations is the key to this technology because it consumes less power than advertising and scanning.

A lot of the nRF specific functionality has already been extracted into a hardware abstraction layer (FruityHal) but more work is necessary to fully decouple the implementation from the underlying stack. Implementing FruityMesh for a different chipset might be little or a lot of work depending on the capabilities and manner of operation of the other chip.

== How is this different from a broadcast mesh?
FruityMesh is based on BLE connections instead of broadcasting and advertising. Some of the advantages of this approach are:
- There are 37 connection channels and only 3 advertising channels which means that packets are delivered with less effort and with less collisions.
- In contrast to a broadcasting mesh, connections can be active at all times while still using less energy than advertising and scanning at times.
- This makes it possible to run on batteries and still have a high throughput and low latency.

One of the drawbacks is, that setting up connections takes time and a node failure can lead to a temporary loss of connectivity for parts of the mesh.
