= IO Module (ID 6)

== Purpose

The _IoModule_ with _ModuleId_ 6 is driving and configuring all GPIOs. E.g. toggling a LED, a motor or reading values from a basic sensor.

== Functionality
The IO module only supports toggling of LEDs and
different pins at the moment. It will be extended to include support for basic sensors that can be read by e.g. analog/digital conversion.

=== Change LED Mode
Changes the LED mode to one of the states. It is possible to turn leds on or off, but also eg. signal number of connections.

[cols="1,2"]
|===
|Mode|Blink pattern

|on|all LEDs are on
|off|all LEDs are off
|connections|if networkId = 1, red LED on + 
if no connections red LED blinking + 
if connected green LED blinking for connection count
|===

[source,C++]
----
//Set led mode
action [nodeId] io led [mode = on / off / connections]

//Switch leds on on all nodes
action 0 io led on
----

=== Set Pins
Sets a pin to either high or low output.

[source,C++]
----
//Configure pins low or high
action [nodeId] io pinset [pinNumber] [mode] ...

//Configure Pins 21 and 22
action 0 io pinset 21 high 22 low
----

[#Identify]
=== Start identification
Starts identification procedure which will blink all board LEDs with a 200ms period for a total of 30 seconds. Can also be handled by other modules to start custom identification. This mode overrules curent led mode.

[source,C++]
----
//Trigger identification
action [nodeId] io identify [mode = on / off]

//Trigger identification
action 0 io identify on
----


[#ImplementationDetails]
=== Implementation Details

The `SET_LED(_RESPONSE)` and `SET_IDENTIFICATION(_RESPONSE)` messages are also transmitted over via `MeshAccessConnections` which are established with the `FmKeyId::ORGANIZATION`.
This is required for devices which are not part of the mesh network, but instead part of the overall organization.
