= Logger

== Purpose

The logger is used to output data on the terminal. It allows filtering for log tags to make development easy and also offers some functionality to log error codes into RAM.

== Functionality

The logger can be used for printing log outputs to the terminal using the `logt` macro. With the `logjson` macro, it is possible to log a json for machine to machine communication. This logging can be removed from the compiled firmware by undefining the `ENABLE_LOGGING` macro or the `ENABLE_JSON_LOGGING` macro. Another function called `trace` will log a string without adding additional information such as the time or the place where the log statement was used.

The logger also has functionality for logging events to the RAM, e.g. `logError` or `logCustomError`. These commands will record the time and the error code into RAM. `logCustomCount` allows you to increase the value each time the method is called. These error codes can be queried using the `get_errors` command of the xref:StatusReporterModule.adoc[StatusReporterModule]. Once the error codes have been requested, the error log is cleared.

The logger and terminal can be used over UART or over Segger RTT. It is also possible to have both log transports enabled at the same time. Use the defines `ACTIVATE_UART` and `ACTIVATE_SEGGER_RTT` to enable this functionality in your featureset.

[#ErrorLog]
== Error Log
Because there are errors that only happen during production or in a test mesh that is not easily debuggable, the Logger supports logging errors to RAM. Each node can store a number of errors in RAM. We allow to store a timestamp, an error code and some extra information. This log can be queried every few minutes or hours by anyone attached to the mesh, e.g. a Gateway. The errors have different significance and some information is logged using a counter that always increments. This statistical information can be used to determine the health of a live mesh and to monitor it. Other errors are more severe but happen less often. For these, a seperate entry that includes the timestamp is stored. Storing the errors is necessary as they might be generated while a node is disconnected from the mesh. The error log will be cleared once the errors have been queried. Reboots are also stored in this log. Once a node fails for any reason, it will store that reason in the error log after it has rebootet. Reasons can include watchdog reboots, reboots due to a firmware update, hardfault, etc,.... To log an error in your custom application, use the `logError` method from the `Logger` class.

== Terminal Commands

=== Toggling Log Tags

Output of specific logTags can be toggled with the following command. A few log tags such as ERROR or WARNING are always logged to the terminal.

[source,C++]
----
debug [tagName]

//E.g. toggle logging for the node
debug node

//E.g. toggle logging for all logs
debug all
----

=== Viewing All Active Log Tags

The following command provides a list of all enabled log tags:

[source,C++]
----
debugtags
----
