= Sensors and Actuators (Firmware)

== Purpose
As a generic way to send sensor measurements and to send commands to actuators, it is possible to use the component_act and component_sense messages. These messages contain a moduleId that is controlled by a vendor. Next, they contain a 2 byte component that can be used to specify a device that is somehow attached to a FruityMesh node. The registerAddress is then used to specify a handle for this value, e.g. a Modbus holding register or a characteristic. The payload is transmitted over the terminal by using base64 or hex-string encoded binary data.

== Messages

=== Message Types
[source, C++]
----
#define MESSAGE_TYPE_COMPONENT_ACT 58 //Actuator messages
#define MESSAGE_TYPE_COMPONENT_SENSE 59 //Sensor messages
----

=== Component Sense Message
The component_sense message is used to transport the result of reads or writes or other sensor values generated by the node.

[source, C++]
----
// Generate a sensor event and send through mesh
// (Only used for debugging)
component_sense [nodeId] [moduleId] [actionType] [component] [registerAddress] [hexString | base64String] {requestHandle=0}

//E.g. broadcast sensor event for module 123 from component 7 and registerAddress 77
component_sense 0 123 0 7 77 AA:BB
----

Following message is used to transport the sensor measurement values across the mesh.

[source, C++]
----
enum actionType {
    UNSPECIFIED = 0, // E.g. Generated by sensor itself
    ERROR_RSP = 1, // Error during READ/WRITE/...
    READ_RSP = 2, // Response following a READ
    WRITE_RSP = 3, // Response following a WRITE_ACK
    CMD_RSP = 4 // Response following a CMD or WRITE
};
----

[cols="1,2,2,4"]
|===
|Bytes|Type|Name|Description

|5|xref:Specification.adoc#connPacketHeader[connPacketHeader]|header|
|1|u8|moduleId|The module that generated this value
|1|u8|requestHandle|Optional request handle, otherwise 0
|1|u8|actionType|One of the above actionTypes
|2|u16|component|Some number identifying the source of the measurements such as a lamp head (*vendor specific*)
|2|u16|registerAddress|An address used to differentiate data transported such as a hardware register number or a message profile ID (*vendor specific*)
|1-...|u8[]|payload|Actual binary data that represents a sensor reading or multiple.
|===

The packet header consumes 12 bytes, which allows for 8 bytes of payload in a single packet and should be enough for most sensor values. For bigger payloads, it will be split.

The output on a sink will be:
[source,javascript]
----
{
	"nodeId": 5,                // sender
	"type": "component_sense",  // discriminator
	"module": 123,              // moduleId
	"requestHandle": 0,
	"actionType" : 0,
	"component" : 7,
	"register" : 77,
    "payload": "abcdeQ=="       // base64 encoded
}
----

IMPORTANT: component and register can also be represented as a string that contains the number in hex representation. The implementation must be able to support both an integer or a string representation of an unsigned hex number. For example: `"component":"0x1234"` and `"register":"0x5678"`.

[#ComponentAct]
=== Actuator message

[source, C++]
----
// Instruct device to write data into a register address
component_act [nodeId] [moduleId] [actionType] [component] [registerAddress] [hexString | base64String] {requestHandle=0}
----

The following message is used to transport write or read requests through the mesh.

[#actuatorActionType]
[source, C++]
----
enum actionType {
    RESERVED = 0, // Unused
    WRITE = 1, // Write without acknowledgement
    READ = 2, // Read a value
    WRITE_ACK = 3, // Write with acknowledgement
    CMD = 4 // Command with cmd response to follow
}
----

[cols="1,2,2,4"]
|===
|Bytes|Type|Name|Description

|5|xref:Specification.adoc#connPacketHeader[connPacketHeader]|header|
|1|u8|moduleId|The module that should act on the message
|1|u8|requestHandle|Optional request handle, otherwise 0
|1|u8|actionType|One of the above actionTypes
|2|u16|component|Some number identifying the destination for the action (*vendor specific*)
|2|u16|registerAddress|An address, e.g. hardware register number or a message profile id where the data should be written (*vendor specific*)
|1-..|u8[]|payload|For READ, this must be a singly byte that represents the number of bytes to read. For WRITE and WRITE_ACK, the payload is the bytes that should be written.
|===

No JSON representation is necessary for the moment as the mesh gateway will not react on component_act messages.
